### ISSUE TITLE
Release 0.13.0

### ISSUE THREAD

**Issue by jagi** [jagi/meteor-astronomy#51]
This issue tracks the release of Astronomy 0.13.0.

- [x] Nested schema definition #42
- [x] Multiple fields validation #65
- [x] Warn about setting not defined field #63
- [ ] Fix document states
- [ ] Fix error with calling the `init` function on every document creation
- [x] Reorganize code
- [ ] Nested fields validation
- [ ] Tests for all features

Moved to the 0.14.0 release.

- [ ] Collection level events and validation  #48 #50 #52 #58

**Comment by dandv** [comment]
Any change to add release tags on GitHub? Would give a good feel of what's been and being added. Thanks!

**Comment by jagi** [comment]
Yes right I will update it now!

**Comment by jagi** [comment]
I started testing 1.0.0-rc.1 version, so go to this issue for more information https://github.com/jagi/meteor-astronomy/issues/97
